language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.7
install:
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script:
  - python manage.py test
